### ISSUE TITLE
error: undefined variable 'loadNixos' on `flake show`

### ISSUE THREAD

**Issue by maxbol** [Cu3PO42/gleaming-glacier#3] opened 2024-02-20 15:18 UTC
First - thanks for a wonderful project! I'm new to nix/nixos and most likely any issues I'm having are a skill issue, so bear with me. :)

I've tried generating an instance of your flake using the install script, (and then generate.sh to generate a user). I then went ahead and upgraded the input pointer of your flake to use the `next` branch since I'm specifically interested in the chroma stuff. Furthermore, I've added some features as well as a NixOS host and a user:

https://github.com/maxbol/nix-dotfiles/tree/3580c8f87cabda21e9b7b2a79be3012dad378c55

When running `nix flake show` in the root of this directory, I get:

```
error: undefined variable 'loadNixos'

       at /nix/store/n1f9aid7aj956fd9kazblr3dkdxicvw6-source/flake.nix:47:29:

           46|       # `withCopperModules = false` to change that behavior.
           47|       nixosConfigurations = loadNixos {
             |                             ^
           48|         dir = ./hosts/nixos;

```

One thing I still find very challenging with the nix language is parsing through the code to find the source of errors like this. There are so many higher order functions, injection shennanigans, various module loading patterns etc that it honestly becomes pretty difficult for me to figure out what is going on. Most likely this will all click for me at some point but right now I'm at a loss. ` loadModules`  seems to be present (presumably in ` copper.lib`  since this is the prefix I'm unpacking with ` with` ), but ` loadNixos`  is missing...

Any idea what might be going wrong here? :)

**Comment by Cu3PO42** [comment] 2024-02-21 08:48
Hi there!

I don't think this as much a skill issue as it is a documentation issue. As mentioned in the README, it only partially applies to the `next` branch. I'm working on new documentation, but that's going to take a while and is also why next isn't yet merged into master. While I have posted about my work before, I wouldn't yet label it as "ready for general consumption". That said, feel free to play around with it and please let me know which hurdles you encounter that may need special care in the docs.

The `loadNixos` function no longer exists and the Flake template you used changed massively in the next branch. Please check [the new template](https://github.com/Cu3PO42/gleaming-glacier/blob/next/templates/system/flake.nix). Yes, it is supposed to be this "empty". All of the loading code that was there before is now happening behind the scenes. The only thing you really need to adjust there is "myprefix" to any namespace of your choice, really. I recommend choosing something based on your username. 

If you've added a feature of your own, the way you include that has changed slightly. While before it would have been available as `copper.feature.<your-feature-name>`, it is now available as `<your-chosen-prefix>.feature.<your-feature-name>`, where the prefix is the one you've chosen in the prior step.

**Comment by maxbol** [comment] 2024-02-21 10:28
Thanks!

I managed to figure that part out and have already gotten the nixos configuration to build :-)

Unfortunately I'm still having some issues with the home-manager stuff.

When evaluating `outputs.homeConfigurations."max@jockey"` with nix REPL I get some sort of infinite recursion error while evaluatinmg the module argument `inputs` in `:anon-1:anon:56:anon-1`... 

This is my home conf:

https://github.com/maxbol/nix-dotfiles/blob/f1994f00cc4e1c75363c379250c1666f83063b71/users/max%40jockey.nix

I've tried commenting out all features, and still the same result.

Do you know what I might be doing wrong here?

Also - for the nixosConfiguration - while I can evaluate `outputs.nixosConfigurations.jockey.config.home-manager.users` without errors, it seems to be empty by default. I am using the `home-manager` feature and can verify that it is being evaluated. Is there some other step I need to take to actually add the user home manager configuration to the system?

**Comment by Cu3PO42** [comment] 2024-02-22 16:54
The issue is likely in your [media](https://github.com/maxbol/nix-dotfiles/blob/f1994f00cc4e1c75363c379250c1666f83063b71/features/home-manager/media.nix) module, where you expect `inputs` as an argument. (Other features expecting the same input would have the same problem.) `inputs` is no longer injected via specialArgs by default, thus Nix tries to resolve it from `config._module.args` (this is just how the module system works), but that value might be set in the module you import, thus leading to infinite recursion. You could configure it to be injected, or instead use `origin.inputs`, which is available by default. Due to the nature of the module system, inputs are not conditionally evaluated, thus commenting out your feature didn't fix the problem.

As for your home configuration, they are not currently automatically injected into NixOS configurations. That is on the list of planned features, for now you'd need to manually import the modules from your config. I like to manage my Home configurations seperately, though, so I do not activate Home-Manager in my NixOS config and just run `nix build .#homeConfigurations."max@jockey".activationPackage` and then `result/activate`.

**Comment by maxbol** [comment] 2024-02-23 13:05
Right you are, I managed to sort the media module now :) 

> for now you'd need to manually import the modules from your config

So cool to get your feedback on this. The best I've come up with so far is a nixos module like this, still a bit limited in that it requires an explicit list of users. If you can think of a better way please let me know!

```
{ config, lib, ... }: let 
  hostName = config.networking.hostName;
  inherit (lib.strings) concatStrings;
  inherit (lib.lists) forEach;
  userDir = userName: concatStrings [userName "@" hostName];

  allUsers = [
    "max"
  ];

  users = builtins.listToAttrs (
    forEach allUsers (user: rec {
      name = userDir user;
      value = import (./. + (concatStrings ["../../../users/" name ".nix"]));
    })
  );
in {
  home-manager.users = users;
}
```

**Comment by maxbol** [comment] 2024-02-23 16:13
Played around with it a bit.

Came up with two different solutions that both seem to do the basic trick of mapping home-manager configurations by user:

```
{ origin, config, lib, ... }: let 
  inherit (lib.strings) concatStrings hasSuffix removeSuffix;
  inherit (builtins) attrNames listToAttrs map filter;
  inherit (origin.inputs) copper;
  inherit (origin.config.gleaming) autoload basepath;
  inherit (copper.lib) loadHome;

  hostName = config.networking.hostName;
  hostSuffix = concatStrings ["@" hostName];
  hasHostSuffix = hasSuffix hostSuffix;
  removeHostSuffix = removeSuffix hostSuffix;

  homeConfigurations = loadHome {
    dir = basepath + "/users";
    specialArgs = autoload.specialArgs;
    modules = autoload.baseModules.home ++ [
      {
        copper.feature.standaloneBase.enable = false;
        copper.feature.nixosBase.enable = true;
      }
    ];
  };

  userConfig = user: homeConfigurations.${user}.config;

  makeUserAttr = user: {
    name = removeHostSuffix user;
    value = userConfig user;
  };

  allUsersWithHost = attrNames homeConfigurations;

  usersForThisHost = filter hasHostSuffix allUsersWithHost;
  users = listToAttrs (map makeUserAttr usersForThisHost);
in {
  home-manager.users = users;
}
```

And:

```
{ origin, config, lib, ... }: let 
  inherit (lib.strings) concatStrings hasSuffix removeSuffix;
  inherit (builtins) attrNames listToAttrs map filter;

  hostName = config.networking.hostName;
  hostSuffix = concatStrings ["@" hostName];
  hasHostSuffix = hasSuffix hostSuffix;
  removeHostSuffix = removeSuffix hostSuffix;

  homeConfigurations = origin.config.flake.homeConfigurations;

  userConfig = user: homeConfigurations.${user}.config // {
    copper.feature.standaloneBase.enable = false;
    copper.feature.nixosBase.enable = true;
  };

  makeUserAttr = user: {
    name = removeHostSuffix user;
    value = userConfig user;
  };

  allUsersWithHost = attrNames homeConfigurations;

  usersForThisHost = filter hasHostSuffix allUsersWithHost;
  users = listToAttrs (map makeUserAttr usersForThisHost);
in {
  home-manager.users = users;
}
```

But for both these solutions, I now run into the following problem when probing `nixosConfigurations.jockey.config.home-manager.users.max` in the REPL:

```
error: evaluation aborted with the following error message: 'Renaming error: option `services.redshift.settings.redshift.brightness-night' does not exist.'
```

With `nixos-rebuild boot --flake ./#jockey` I get two different issues depending on version:

First version (triggering loadHome):

```
error: The option `home-manager.users.max.copper.chroma.palette.enable' is read-only, but it's set multiple times.
```

Second version (referencing homeConfigurations output):

```
error: evaluation aborted with the following error message: 'Renaming error: option `home.pointerCursor.x11.defaultCursor' does not exist.'
```

So I'm stuck again... Feels like this should be trivial but I'm having a real hard time of it :D

**Comment by Cu3PO42** [comment] 2024-02-25 13:24
I'm glad you were able to figure it out.

> causes all HM modules to be evaluated again.

This is exactly right. `homeManagerConfiguration` is, in essence, the constructor for a configuration, accepting your modules. The NixOS option `home-manager.users.<user>` also needs these modules to pass to the contructor internally. Thus, by using the pre-computed `flake.homeConfigurations` you are processing the configuraiton again.

Your solution is super valid, though I will likely tackle it a bit differently in upstream if and when I get around to it.

I'll go ahead and close this issue since I believe you were able to resolve the original problem.

**Closed by Cu3PO42** 2024-02-25 13:24 UTC
